Terraform 2
Otus-DevOps-2018-05/AlexeyAltunin_infra pull request #6
Opened 2018-07-03 19:07 UTC by AlexeyAltunin

# Выполнено ДЗ № 7

 - [+] Основное ДЗ
 - [-] Задание со *

## В процессе сделано:
 - Разбиение на модули
 - Настроил параметризацию
 - Переиспользование модулей для Prod and Stage
 - Работа с реестром модулей

## Как запустить проект:
 - terraform apply

## Как проверить работоспособность:
 - Travis

## PR checklist
 - [+] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2018-07-13 17:35 UTC, Nklya commented
<img width="287" alt="image" src="https://user-images.githubusercontent.com/26086394/42705529-4870b8dc-86dc-11e8-909d-1accaa9ee201.png">

галочки ставятся не так

2018-07-13 17:36 UTC, Nklya requested changes
Ревью будет выполнено после мержа предыдущих принятых ДЗ

2018-07-17 13:53 UTC, AlexeyAltunin commented
Done

2018-07-17 19:21 UTC, Nklya approved these changes
Добрый вечер.

Алексей, условия ДЗ выполнены, все реализовано относительно ок 👍

2018-07-17 19:21 UTC, Nklya commented on packer/app.json
> +    "source_image_family": "ubuntu-1604-lts",
source_image_family тоже стоит делать обязательным

2018-07-17 19:21 UTC, Nklya commented on packer/db.json
> +    "source_image_family": "ubuntu-1604-lts",
source_image_family тоже стоит делать обязательным

2018-07-17 19:21 UTC, Nklya commented on terraform/stage/variables.tf
> +  default     = "reddit-app-base-20180701-195953"
Зачем использовать полное имя образа, когда есть image-family, который reddit-app-base???

2018-07-17 19:21 UTC, Nklya commented on terraform/variables.tf
> +  default = "reddit-db-base-20180701-200439"
Большая часть переменных здесь больше не нужна

2018-07-17 19:21 UTC, Nklya commented on terraform/prod/terraform.tfvars.example
> +disk_image = "reddit-base"
Переменные в terraform.tfvars.example стоит актуализировать.
disk_image уже не используется

2018-07-17 19:21 UTC, Nklya commented on terraform/modules/db/variables.tf
> +  default = "reddit-db-base-20180701-200439"
Модули - это выделенные абстрактные сущности.
Задавать здесь default - антипаттерн

2018-07-17 19:25 UTC, merged