Ansible 2
Otus-DevOps-2018-05/AlexeyAltunin_infra pull request #8
Opened 2018-07-07 10:19 UTC by AlexeyAltunin

# Выполнено ДЗ № 9

 - [+] Основное ДЗ
 - [-] Задание со *

## В процессе сделано:
 - Рассмотрены различные подходы от прямого к более гибкому
 - Один плейбук = один сценарий
 - Разбиение на сценарии в рамках одного плейбук
 - Разбиение на несколько плейбуков (избавляемся от тегов)
 - Замена sh криптов в packer provision на ansible playbook 

## Как запустить проект:
 - ansible-playbook site.yml

## Как проверить работоспособность:
 - перейти по ссылке http://${app-ip}:9292

## PR checklist
 - [+] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2018-07-17 19:23 UTC, Nklya requested changes
Сейчас нужно:
1. Смежить предыдущие PR
2. Прописать полностью имя в профиле GitHub

2018-07-17 19:27 UTC, AlexeyAltunin commented
@Nklya Сделано

2018-07-18 10:59 UTC, Nklya approved these changes
Добрый день.

Алексей, условия ДЗ выполнены, все реализовано хорошо 👍

2018-07-18 10:59 UTC, Nklya commented on terraform/stage/variables.tf
> +  default     = "reddit-app-base-20180706-221410"
Зачем использовать полное имя образа, если есть image-family???
Достаточно же один раз вписать reddit-app-base

2018-07-24 19:32 UTC, merged